'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("N_ListR.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to $	101	שטייניץ רות	201	ruthizz@012.net.il	050-428-8552	@
        '''$	102	אימרל שרה	202			@
        '''$	103	שקלובין מרתה	203	martasklowin@gmail.com		@
        '''$	104	ארמן צ&apos;רלס	204	charlesarman@aol.com	053-609-6364	@
        '''$	105	בלומנפלד רות	205	מטפלת לילי	050-777-3796	@
        '''$	106	דה-בוטון קולט	206		058-441-3185	@
        '''$	107	שטיינברג אביבה	207	Avivasteinberg@gmail.com		@
        '''$	108	קרצ&apos;מר פנינה	208	Pninakretchmer@gmail.com	050-656-8376	@
        '''$	109	עטיה נעמי	209			@
        '''$	110	אייל ורה	210	Vera.eyal@gmail.com	054-574-1966	@
        '''$	111	אלקנה יהודית	213	yehuditelk [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property N_LIST() As String
            Get
                Return ResourceManager.GetString("N_LIST", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
